### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-drift-module#1]
### Core
- [x] Fix the JavaScript widget so that it allows other widget modules to load.
- [ ] Fix admin configurations page.
- [ ] Find a solution to extend module if possible.
- [x] Removing Backend Issues (#2)

### Translations
`TBA`
